# Generated by Django 4.2.9 on 2024-04-08 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
