# Generated by Django 4.2.9 on 2024-04-08 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malls', '0003_alter_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='product',
            field=models.ManyToManyField(related_name='buy', through='malls.Order', to='malls.product'),
        ),
    ]
