# Generated by Django 4.2.9 on 2024-03-29 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('insert_time', models.DateTimeField(auto_now=True)),
                ('modi_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
