# Generated by Django 4.2.9 on 2024-03-29 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memo',
            old_name='content',
            new_name='memo',
        ),
    ]
